version: "3.8"
services:
  
  signal-api:
    image: bbernhard/signal-cli-rest-api:latest
    container_name: signal-api
    ports:
      - "8000:8080"
    volumes:
      - ./signal-cli:/home/.local/share/signal-cli
    environment:
      - MODE=native
    restart: always


